#Load libraries
```{r}
library(stats)
library(factoextra)
library(tcplfit2)
library(patchwork)
library(cowplot)
library(MASS)
library(gridExtra)
```
#Global level Principal component analysis, Mahalanobis distance calculations, and Concentration-response analysis
```{r}
test_chem_well <- read_csv(
  file.path(pipeline_output_path, "Well-level_data_simplified_categories.csv")
)

# Move first column to row names
test_chem_well <- as.data.frame(test_chem_well)
rownames(test_chem_well) <- test_chem_well[[1]]
test_chem_well <- test_chem_well[, -1]

#Load in from sheet 2 so feature names are correct
well_data <- test_chem_well

#Principal component analysis (PCA)
pca <- prcomp(well_data, center = TRUE, scale = TRUE)

#Scree plot
scree_plot <- fviz_eig(pca, addlabels = T, ylim = c(0,75), main = paste0("Scree plot"))  
scree_plot

#Calculate the number of PCs that describe >95% variance
cumulative_prop <- cumsum(pca$sdev^2)/sum(pca$sdev^2)

#PC_90 <- length(which(cumulative_prop<0.90))+1
PC_95 <- length(which(cumulative_prop<0.95))+1
#PC_99 <- length(which(cumulative_prop<0.99))+1

#Rotation Matrix
a <- ncol(pca$rotation)

pca_x <- as.data.frame(pca$x)
pca_x <- as.data.frame(cbind(chem = rownames(well_data), pca_x)) 

####SD >1
#pca_x <- pca$x[, pca$sdev > 1, drop = FALSE]

#pca_x <- as.data.frame(cbind(chem = rownames(well_data), pca_x)) 
####

ctrl_pc <- pca_x %>%
  filter(grepl(ctrl_group, chem))

ctrl_pc <- ctrl_pc[,-c(1)]

#DMSO_mean <- colMeans(DMSO_pc)
ctrl_mean <- apply(ctrl_pc, 2, mean)

dat <- as.matrix(well_data) %*% pca$rotation[,1:PC_95]
#dat <- pca$x[, 1:PC_95]

#Covariance Matrix
Cov <- cov(dat)

#Checkpoint
det(Cov)
isSymmetric(Cov)

solved_cov <- ginv(Cov)

#Mahalanobis distance determination

mahal_dist <- mahalanobis(dat, ctrl_mean, solved_cov, inverted = T) 

mahal_dist <- as.data.frame(mahal_dist)

mahal_dist_sq <- sqrt(mahal_dist)
mahal_dist <- mahal_dist_sq

mahal_dist <- cbind(chem = rownames(well_data), mahal_dist)

sample <- as.data.frame(mahal_dist$chem)
colnames(sample) <- "sample"

sample <- tibble(sample) %>%
  separate(sample, c("chem", "concentration", "Well", "Plate"), sep = "_", remove = T)

mahal_dist <- cbind(sample, mahal_dist = mahal_dist$mahal_dist)

mahal_dist$concentration <- as.numeric(mahal_dist$concentration)

mahal_dist <- mahal_dist %>%
  group_by(chem) %>%
  mutate(conc_count = length(unique(concentration)))

mahal_ctrl <- mahal_dist %>%
  filter(chem == ctrl_group)

mahal_dist <- mahal_dist %>%
  filter(conc_count > 3) 

mahal_dist <- rbind(mahal_dist, mahal_ctrl)

mahal_dist$exp <- exp_name
```
#Plot Malanobis distance 
```{r}
chem_list <- unique(mahal_dist$chem)
plate <- unique(mahal_dist$Plate)

mahal_dist[mahal_dist$chem == ctrl_group, ]$concentration <- 1


lapply(plate, function(plate_i) {

  p <- ggplot(mahal_dist[mahal_dist$Plate == plate_i, ], 
              aes(x = concentration, y = mahal_dist, colour = chem)) + 
    geom_point() + 
    geom_hline(
      yintercept = median(mahal_ctrl$mahal_dist),
      linetype = "dashed",
      color = "maroon4"
    ) +
    geom_ribbon(
      aes(
        ymin = median(mahal_ctrl$mahal_dist) - mad(mahal_ctrl$mahal_dist),
        ymax = median(mahal_ctrl$mahal_dist) + mad(mahal_ctrl$mahal_dist)
      ),
      fill = "thistle3",
      colour = NA,
      alpha = 0.5
    ) +
    scale_y_continuous() +
    scale_x_log10() +
    xlab("Concentration (\u03BCM)") +
    ylab("Mahalanobis Distance") +
    theme_classic() +
    theme(
      legend.position = "none",
      axis.title.x = element_text(size = 17, margin = margin(t = 15)),
      axis.title.y = element_text(size = 17, margin = margin(r = 15)),
      axis.text.x = element_text(size = 12),
      axis.text.y = element_text(size = 12)
    ) +
    facet_wrap(vars(chem), scales = "free") +
    theme(strip.text.x = element_text(size = 12, face = "bold"))

  ggsave(
    filename = file.path(plots, paste0("Plate_", plate_i, "_Global_Mahalanobis.png")), plot = p,width = 50, height = 35, units = "cm")

  p
})


p_global <- ggplot(mahal_dist, 
                   aes(x = concentration, y = mahal_dist, colour = chem)) + 
  geom_point(size = 3) + 
  geom_hline(
    yintercept = median(mahal_ctrl$mahal_dist),
    linetype = "dashed",
    color = "maroon4"
  ) +
  geom_ribbon(
    aes(
      ymin = median(mahal_ctrl$mahal_dist) - mad(mahal_ctrl$mahal_dist),
      ymax = median(mahal_ctrl$mahal_dist) + mad(mahal_ctrl$mahal_dist)
    ),
    fill = "thistle3",
    colour = NA,
    alpha = 0.5
  ) +
  scale_y_continuous() +
  scale_x_log10() +
  xlab("Concentration (\u03BCM)") +
  ylab("Mahalanobis Distance") +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.title.x = element_text(size = 17, margin = margin(t = 15)),
    axis.title.y = element_text(size = 17, margin = margin(r = 15)),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12)
  ) +
  facet_wrap(vars(chem), scales = "free") +
  theme(strip.text.x = element_text(size = 12, face = "bold"))

p_global
ggsave(filename = file.path(plots, paste0(exp_name, "_Global_Mahalanobis.png")),plot = p_global, width = 50,height = 35,units = "cm")


mahal_dist <- mahal_dist %>%
  separate(Well, into = c("Row", "Column"), sep = "(?<=\\D)(?=\\d)")

mahal_dist$Column <- factor(mahal_dist$Column, levels = as.character(1:12))
mahal_dist$Row <- factor(mahal_dist$Row, levels = LETTERS[8:1])


mahaldist_hm <- ggplot(mahal_dist, aes(x = Column, y = Row, fill = mahal_dist)) +
  geom_tile() +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(
    title = element_text(size = 13),
    axis.title.x = element_text(size = 16, margin = margin(t = 15)),
    axis.title.y = element_text(size = 16, margin = margin(r = 15)),
    axis.text.x = element_text(size = 14, colour = "black"),
    axis.text.y = element_text(size = 14, colour = "black", margin = margin(r = 5)),
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 13, colour = "black")
  ) +
  labs(
    title = "Mahalanobis distance of each well from the plate mean",
    x = "Columns",
    y = "Rows",
    fill = "Mahalanobis\nDistance"
  ) +
  facet_grid(rows = vars(Plate))

mahaldist_hm

ggsave(
  filename = file.path(plots, "Mahalanobis_distance_heatmaps.png"), plot = mahaldist_hm,width = 20,height = 60, units = "cm")
```

#tcplfit2
```{r}
test_chem_res <- mahal_dist %>%
  filter(chem !=ctrl_group)

#####Tcplfit2 to derive benchmark concentrations#####

chem_list <- unique(test_chem_res$chem)

DMSO_dist <- mahal_dist %>%
  filter(chem == ctrl_group)

vehicle_ctrl <- mahal_dist %>%
  filter(chem == ctrl_group) %>%
  summarise(Median = median(mahal_dist, na.rm=T), 
            nMad = mad(mahal_dist, constant=1.4826, na.rm=T))

#Function to model concentration-response using concRespCore of tcplfit2
conc_res_modeling <- function(test_chem, vehicle_ctrl){ 
  
  row <- list(conc = as.numeric(test_chem$concentration),
              resp = test_chem$mahal_dist,
              bmed = vehicle_ctrl$Median,
              cutoff = vehicle_ctrl$nMad,
              onesd = vehicle_ctrl$nMad,
              name = paste0(test_chem$chem[1]),
              assay = "Mahalanobis distance (cutoff = 1)")
  
  concRespCore(row, conthits = TRUE, aicc = FALSE, force.fit = FALSE,  bidirectional = TRUE,
               fitmodels=c("cnst", "hill", "poly1", "poly2", "pow", "exp2", "exp3","exp4", "exp5"))
  
}




#Model concentration-response for each chemical and plot individually  
tcpl_results <- lapply(chem_list, function(x){
  chem_data <- test_chem_res %>%
    filter(chem == x)
  tcpl_chem <- conc_res_modeling(chem_data, vehicle_ctrl)
  
  if(tcpl_chem$hitcall > 0.9){
    png(file = paste0(plots, "_tcplfit_curves.png"))
    concRespPlot(tcpl_chem, ymin=min(chem_data$mahal_dist)-5, ymax=max(chem_data$mahal_dist)+10, draw.error.arrows = FALSE)
    dev.off()
  }
  
  tcpl_chem
}) %>%
      do.call(rbind, .)



tcpl_testchem <- tcpl_results %>%
  mutate(
    minDose = min(conc, na.rm = TRUE),
    maxDose = max(conc, na.rm = TRUE),

    removal_reason = case_when(
      hitcall < 0.9            ~ "low_hitcall",
      is.na(bmdl)              ~ "missing_bmdl",
      is.na(bmdu)              ~ "missing_bmdu",
     # bmd < minDose            ~ "bmd_below_minDose",
      #bmd > maxDose            ~ "bmd_above_maxDose",
      TRUE                     ~ "kept"
    ),

    keep = removal_reason == "kept",

    bmd  = ifelse(keep, bmd, NA),
    bmdl = ifelse(keep, bmdl, NA),
    bmdu = ifelse(keep, bmdu, NA)
  ) %>%
  ungroup()



ggsave(
  filename = file.path(plots, "Global_BMC__sqrt_neworder.png"),
  plot = ggplot(tcpl_testchem, aes(x = bmd, y = name, colour = name)) +
    geom_point(size = 2) +
    geom_errorbar(aes(xmin = bmdl, xmax = bmdu), width = 0.2) +
    scale_x_log10() +
    theme_bw() +
    theme(
      legend.position = "none",
      axis.title.x = element_text(size = 13, margin = margin(t = 15)),
      axis.title.y = element_text(size = 13),
      axis.text.x = element_text(size = 10, colour = "black"),
      axis.text.y = element_text(size = 6, colour = "black", margin = margin(r = 5)),
      strip.text.x = element_text(size = 9, face = "bold"),
      strip.background = element_rect(fill = NA),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
    ) +
    xlab("Median Best BMC (1 MAD above vehicle control) \u03BCM") +
    ylab("Chemicals"),
  width = 40,
  height = 20,
  units = "cm"
)

tcpl_testchem$exp_name <- exp_name

```

