#Load libraries

```{r}
library(stats)
library(factoextra)
library(tcplfit2)
library(patchwork)
library(cowplot)
library(MASS)
library(gridExtra)
library(purrr)
library(readr)
library(tibble)  
library(stringr)
library(tidyr)
library(viridisLite)

```



#SQRT Category level 
```{r}
dir.create(
  file.path(pipeline_output_path, "tcplfit_results_cat"),
  showWarnings = FALSE,
  recursive = TRUE
)
path <- file.path(
  pipeline_output_path,
  "feature_results",
  "test_chem_cat_pearson_0.9_common.csv"
)

# --- Load the well-level data ---
test_chem_well <- read_csv(
  path,
  show_col_types = FALSE,
  name_repair = "minimal"
) |>
  as.data.frame()

# First column contains row names
rownames(test_chem_well) <- test_chem_well[[1]]
test_chem_well <- test_chem_well[, -1]

# --- Load the matching category labels ---
ft_path <- str_replace(
  path,
  "\\.csv$",
  "_ft_colnames2.csv"
)

ft_colnames2 <- read_csv(
  ft_path,
  show_col_types = FALSE
)$features


well_data <- test_chem_well

#Transpose 
test_chem_well_cat <- t(test_chem_well) |>
  as.data.frame()

# Add category labels as a COLUMN
test_chem_well_cat <- cbind(
  features = ft_colnames2,
  test_chem_well_cat
)

rownames(test_chem_well_cat) <- NULL
  
#Filter out categories with fewer than 2 features ---
cat_lev_data <- test_chem_well_cat %>%
  group_by(features) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  filter(count > 1)
cat_lev_data <- cat_lev_data[,-c(ncol(cat_lev_data))]

samples <- colnames(cat_lev_data)[2:ncol(cat_lev_data)]

ft_cats <- unique(cat_lev_data$features)
#Eliminate categories with no variance across samples

cat_lev_data <- lapply(ft_cats, function(x){
  cat_dat <- well_data[, grep(x, colnames(well_data))]
  variances <- apply(cat_dat, 2, var)
  cat_dat <- cat_dat[, variances != 0] 
  cat_dat
  }) %>%
  do.call(cbind,.)
#PCA by category
pca_cat <- lapply(ft_cats, function(x){
  cat_dat <- cat_lev_data[, grep(x, colnames(cat_lev_data))]
  pca <- prcomp(cat_dat, center = TRUE, scale = TRUE)
  return (pca)
}) %>%
  setNames(ft_cats)

cat_mahal_dist <- lapply(ft_cats, function(x){
  
  pca <- pca_cat[[x]]
  
  cumulative_prop <- cumsum(pca$sdev^2)/sum(pca$sdev^2)
  PC_95 <- length(which(cumulative_prop<0.95))+1
  
  pca_x <- as.data.frame(pca$x)
  pca_x <- as.data.frame(cbind(chem = samples, pca_x)) 
  
  ctrl_pc <- pca_x %>% filter(grepl(ctrl_group, chem))
  ctrl_pc <- ctrl_pc[,-c(1)]
  ctrl_mean <- colMeans(ctrl_pc)
  
  cat_dat <- well_data[, grep(x, colnames(well_data))]
  zero_col <- sapply(cat_dat, function(col) all(col == 0))
  cat_dat <- cat_dat[,!zero_col]
  
  dat <- as.matrix(cat_dat) %*% pca$rotation[,1:PC_95]
  
  #Covariance Matrix
  Cov <- cov(dat)
  
  #Checkpoint
  det(Cov)
  isSymmetric(Cov)
  
  #Mahalanobis distance determination
  
  mahal_dist <- mahalanobis(dat, ctrl_mean, Cov, inverted = F) 
  
  mahal_dist <- as.data.frame(mahal_dist)
  mahal_dist  <- as.data.frame(sqrt(mahal_dist))
  mahal_dist <- cbind(chem = rownames(well_data), mahal_dist)
  
  sample_info <- mahal_dist$chem
  sample_info <- tibble(sample_info) %>%
    separate(sample_info, c("chem", "concentration", "well", "well2"), sep = "_", remove = T)
  
  sample_info$well <- paste0(sample_info$well, "_", sample_info$well2)
  
  mahal_dist <- cbind(sample_info[1:3], mahal_dist = mahal_dist$mahal_dist)
  
  return(mahal_dist)
  }) %>%
  setNames(ft_cats)

#pick one at random to pull chem list
chem_list <- unique(cat_mahal_dist[["cells_DNA_Granularity"]][["chem"]])

# Separate categorical Mahalanobis distances by chemical
mahal_dist_chem <- lapply(chem_list, function(x){
  chemical <- x
  
  chem_dat <- lapply(ft_cats, function(y){
    chem_dat <- filter(cat_mahal_dist[[y]], chem == chemical)
    return(chem_dat)}) %>%
    setNames(ft_cats)
  
  chem_dat <- do.call(rbind, chem_dat)
  
  return(chem_dat)}) %>%
  setNames(chem_list) %>%
  do.call(rbind, .)

mahal_dist_chem$feat <- rownames(mahal_dist_chem)
mahal_dist_chem$feat <- str_extract(mahal_dist_chem$feat, "(?<=\\.).*?(?=\\.)")
rownames(mahal_dist_chem) <- NULL


#Per-chemical Mahalanobis plots
#lapply(chem_list, function(x) {
#  p <- ggplot(
#     mahal_dist_chem[mahal_dist_chem$chem == x, ],
#      aes(x = as.numeric(concentration), y = mahal_dist, colour = feat)
#    ) +
#      geom_point() +
#      scale_y_continuous() +
#      scale_x_log10() +
#       scale_color_manual(
#    values = turbo(length(unique(mahal_dist_chem$feat)))
#  ) +
#      xlab("Concentration (\u03BCM)") + ylab("Mahalanobis Distance") +
#      theme_classic() +
#      theme(
#        legend.position = "none",
#        axis.title.x = element_text(size = 20, margin = margin(t = 15)),
#        axis.title.y = element_text(size = 20, margin = margin(r = 15), angle = 90),
#       axis.text.x = element_text(size = 11, colour = "black"),
#        axis.text.y = element_text(size = 11, colour = "black"),
#        strip.text.x = element_text(size = 12, face = "bold"),
#        strip.background = element_rect(fill = NA),
#        axis.line = element_line(linewidth = 1)
#      ) +
#      facet_wrap(vars(feat), scales = "free") 

# ggsave(
#   filename = file.path(plots, paste0(x, file_label, "_Categorical_mahalanobis.png")),
#   plot = p, width = 45, height = 45, units = "cm"
# )
#  })

#tcplfit2 concentration-response modeling per category ---
mahal_dist_chem <- as.data.frame(mahal_dist_chem)

test_chem_res <- mahal_dist_chem |> dplyr::filter(chem != ctrl_group)

conc_res_modeling <- function(test_chem, vehicle_ctrl) {
    row <- list(
      conc   = as.numeric(test_chem$concentration),
      resp   = test_chem$mahal_dist,
      bmed   = vehicle_ctrl$Median,
      cutoff = vehicle_ctrl$nMad,
      onesd  = vehicle_ctrl$nMad,
      name   = paste0(test_chem$chem[1], "_", test_chem$feat[1]),
      assay  = "Mahalanobis distance (cutoff = 1)"
    )
    tcplfit2::concRespCore(
      row, conthits = TRUE, aicc = TRUE, force.fit = FALSE, bidirectional = TRUE,
      fitmodels = c("cnst", "hill", "poly1", "poly2", "pow", "exp2", "exp3", "exp4", "exp5")
    )
  }

chem_list_i <- unique(test_chem_res$chem)
feats <- unique(test_chem_res$feat)

vehicle_ctrl <- mahal_dist_chem |>
    dplyr::filter(chem == ctrl_group) |>
    dplyr::summarise(
      Median = median(mahal_dist, na.rm = TRUE),
      nMad   = mad(mahal_dist, constant = 1.4826, na.rm = TRUE)
    )

tcpl_results_cat_i <- lapply(chem_list_i, function(x) {
    chem_data <- test_chem_res[test_chem_res$chem == x, ]

    lapply(feats, function(y) {
      chem_data_y <- chem_data |> dplyr::filter(grepl(y, feat))
      conc_res_modeling(chem_data_y, vehicle_ctrl)
      
  }) |> do.call(rbind, args = _)
  }) |> do.call(rbind, args = _)

  split_col <- stringr::str_split_fixed(tcpl_results_cat_i$name, "_", 2)
  tcpl_results_cat_i <- cbind("chem" = split_col[, 1], "feat" = split_col[, 2], tcpl_results_cat_i[, -1])

  tcpl_results_cat_i <- tcpl_results_cat_i |>
    dplyr::mutate(
      minDose = min(conc, na.rm = TRUE),
      maxDose = max(conc, na.rm = TRUE),
      removal_reason = dplyr::case_when(
        hitcall < 0.9   ~ "low_hitcall",
        is.na(bmdl)     ~ "missing_bmdl",
        is.na(bmdu)     ~ "missing_bmdu",
        TRUE            ~ "kept"
      ),
      keep = removal_reason == "kept",
      bmd  = ifelse(keep, bmd,  NA),
      bmdl = ifelse(keep, bmdl, NA),
      bmdu = ifelse(keep, bmdu, NA)
    ) |>
    dplyr::ungroup() |>
    dplyr::filter(er < 0.99)

  tcpl_results_cat_i$exp_name <- exp_name

  # --- BMC plot ---
BMC_plot <- ggplot(tcpl_results_cat_i, aes(x = bmd, y = feat, colour = feat)) +
    geom_point(size = 3) +
    geom_errorbar(aes(xmin = bmdl, xmax = bmdu), width = 0.2) +
    scale_x_log10() +
    xlab("Best BMC (1MAD above vehicle control median) \u03BCM") +
    ylab("Feature Category") +
    theme_bw() +
    theme(
      legend.position = "none",
      axis.title.x = element_text(size = 17, margin = margin(t = 20)),
      axis.title.y = element_text(size = 17),
      axis.text.x  = element_text(size = 12, colour = "black"),
      axis.text.y  = element_text(size = 6, colour = "black", margin = margin(r = 5)),
      strip.text.x = element_text(size = 12, face = "bold"),
      strip.background = element_rect(fill = NA),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
    ) +
    facet_wrap(vars(chem)) +
    ggtitle(paste0("Categorical BMC"))

ggsave(
    filename = file.path(plots, paste0("Categorical_BMC", ".png")),
    plot = BMC_plot, width = 25, height = 35, units = "cm"
  )

  # --- Save tcpl results table ---
write_csv(
    tcpl_results_cat_i,
    file.path(
      pipeline_output_path, "tcplfit_results_cat",
      paste0("tcplfit_results_cat_0.9_common", ".csv")))
message("Done (category-level): ", basename(path))

```
#NOTSQRT Category level 
```{r}
dir.create(
  file.path(pipeline_output_path, "tcplfit_results_cat_NOTSQRT"),
  showWarnings = FALSE,
  recursive = TRUE
)
path <- file.path(
  pipeline_output_path,
  "feature_results",
  "test_chem_cat_pearson_0.9_common.csv"
)

# --- Load the well-level data ---
test_chem_well <- read_csv(
  path,
  show_col_types = FALSE,
  name_repair = "minimal"
) |>
  as.data.frame()

# First column contains row names
rownames(test_chem_well) <- test_chem_well[[1]]
test_chem_well <- test_chem_well[, -1]

# --- Load the matching category labels ---
ft_path <- str_replace(
  path,
  "\\.csv$",
  "_ft_colnames2.csv"
)

ft_colnames2 <- read_csv(
  ft_path,
  show_col_types = FALSE
)$features


well_data <- test_chem_well

#Transpose 
test_chem_well_cat <- t(test_chem_well) |>
  as.data.frame()

# Add category labels as a COLUMN
test_chem_well_cat <- cbind(
  features = ft_colnames2,
  test_chem_well_cat
)

rownames(test_chem_well_cat) <- NULL
  
#Filter out categories with fewer than 2 features ---
cat_lev_data <- test_chem_well_cat %>%
  group_by(features) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  filter(count > 1)
cat_lev_data <- cat_lev_data[,-c(ncol(cat_lev_data))]

samples <- colnames(cat_lev_data)[2:ncol(cat_lev_data)]

ft_cats <- unique(cat_lev_data$features)
#Eliminate categories with no variance across samples

cat_lev_data <- lapply(ft_cats, function(x){
  cat_dat <- well_data[, grep(x, colnames(well_data))]
  variances <- apply(cat_dat, 2, var)
  cat_dat <- cat_dat[, variances != 0] 
  cat_dat
  }) %>%
  do.call(cbind,.)
#PCA by category
pca_cat <- lapply(ft_cats, function(x){
  cat_dat <- cat_lev_data[, grep(x, colnames(cat_lev_data))]
  pca <- prcomp(cat_dat, center = TRUE, scale = TRUE)
  return (pca)
}) %>%
  setNames(ft_cats)

cat_mahal_dist <- lapply(ft_cats, function(x){
  
  pca <- pca_cat[[x]]
  
  cumulative_prop <- cumsum(pca$sdev^2)/sum(pca$sdev^2)
  PC_95 <- length(which(cumulative_prop<0.95))+1
  
  pca_x <- as.data.frame(pca$x)
  pca_x <- as.data.frame(cbind(chem = samples, pca_x)) 
  
  ctrl_pc <- pca_x %>% filter(grepl(ctrl_group, chem))
  ctrl_pc <- ctrl_pc[,-c(1)]
  ctrl_mean <- colMeans(ctrl_pc)
  
  cat_dat <- well_data[, grep(x, colnames(well_data))]
  zero_col <- sapply(cat_dat, function(col) all(col == 0))
  cat_dat <- cat_dat[,!zero_col]
  
  dat <- as.matrix(cat_dat) %*% pca$rotation[,1:PC_95]
  
  #Covariance Matrix
  Cov <- cov(dat)
  
  #Checkpoint
  det(Cov)
  isSymmetric(Cov)
  
  #Mahalanobis distance determination
  
  mahal_dist <- mahalanobis(dat, ctrl_mean, Cov, inverted = F) 
  
  mahal_dist <- as.data.frame(mahal_dist)
  mahal_dist  <- as.data.frame(mahal_dist)
  mahal_dist <- cbind(chem = rownames(well_data), mahal_dist)
  
  sample_info <- mahal_dist$chem
  sample_info <- tibble(sample_info) %>%
    separate(sample_info, c("chem", "concentration", "well", "well2"), sep = "_", remove = T)
  
  sample_info$well <- paste0(sample_info$well, "_", sample_info$well2)
  
  mahal_dist <- cbind(sample_info[1:3], mahal_dist = mahal_dist$mahal_dist)
  
  return(mahal_dist)
  }) %>%
  setNames(ft_cats)

#pick one at random to pull chem list
chem_list <- unique(cat_mahal_dist[["cells_DNA_Granularity"]][["chem"]])

# Separate categorical Mahalanobis distances by chemical
mahal_dist_chem <- lapply(chem_list, function(x){
  chemical <- x
  
  chem_dat <- lapply(ft_cats, function(y){
    chem_dat <- filter(cat_mahal_dist[[y]], chem == chemical)
    return(chem_dat)}) %>%
    setNames(ft_cats)
  
  chem_dat <- do.call(rbind, chem_dat)
  
  return(chem_dat)}) %>%
  setNames(chem_list) %>%
  do.call(rbind, .)

mahal_dist_chem$feat <- rownames(mahal_dist_chem)
mahal_dist_chem$feat <- str_extract(mahal_dist_chem$feat, "(?<=\\.).*?(?=\\.)")
rownames(mahal_dist_chem) <- NULL


#Per-chemical Mahalanobis plots
#lapply(chem_list, function(x) {
#  p <- ggplot(
#     mahal_dist_chem[mahal_dist_chem$chem == x, ],
#      aes(x = as.numeric(concentration), y = mahal_dist, colour = feat)
#    ) +
#      geom_point() +
#      scale_y_continuous() +
#      scale_x_log10() +
#       scale_color_manual(
#    values = turbo(length(unique(mahal_dist_chem$feat)))
#  ) +
#      xlab("Concentration (\u03BCM)") + ylab("Mahalanobis Distance") +
#      theme_classic() +
#      theme(
#        legend.position = "none",
#        axis.title.x = element_text(size = 20, margin = margin(t = 15)),
#        axis.title.y = element_text(size = 20, margin = margin(r = 15), angle = 90),
#       axis.text.x = element_text(size = 11, colour = "black"),
#        axis.text.y = element_text(size = 11, colour = "black"),
#        strip.text.x = element_text(size = 12, face = "bold"),
#        strip.background = element_rect(fill = NA),
#        axis.line = element_line(linewidth = 1)
#      ) +
#      facet_wrap(vars(feat), scales = "free") 

# ggsave(
#   filename = file.path(plots, paste0(x, file_label, "_Categorical_mahalanobis.png")),
#   plot = p, width = 45, height = 45, units = "cm"
# )
#  })

#tcplfit2 concentration-response modeling per category ---
mahal_dist_chem <- as.data.frame(mahal_dist_chem)

test_chem_res <- mahal_dist_chem |> dplyr::filter(chem != ctrl_group)

conc_res_modeling <- function(test_chem, vehicle_ctrl) {
    row <- list(
      conc   = as.numeric(test_chem$concentration),
      resp   = test_chem$mahal_dist,
      bmed   = vehicle_ctrl$Median,
      cutoff = vehicle_ctrl$nMad,
      onesd  = vehicle_ctrl$nMad,
      name   = paste0(test_chem$chem[1], "_", test_chem$feat[1]),
      assay  = "Mahalanobis distance (cutoff = 1)"
    )
    tcplfit2::concRespCore(
      row, conthits = TRUE, aicc = TRUE, force.fit = FALSE, bidirectional = TRUE,
      fitmodels = c("cnst", "hill", "poly1", "poly2", "pow", "exp2", "exp3", "exp4", "exp5")
    )
  }

chem_list_i <- unique(test_chem_res$chem)
feats <- unique(test_chem_res$feat)

vehicle_ctrl <- mahal_dist_chem |>
    dplyr::filter(chem == ctrl_group) |>
    dplyr::summarise(
      Median = median(mahal_dist, na.rm = TRUE),
      nMad   = mad(mahal_dist, constant = 1.4826, na.rm = TRUE)
    )

tcpl_results_cat_i <- lapply(chem_list_i, function(x) {
    chem_data <- test_chem_res[test_chem_res$chem == x, ]

    lapply(feats, function(y) {
      chem_data_y <- chem_data |> dplyr::filter(grepl(y, feat))
      conc_res_modeling(chem_data_y, vehicle_ctrl)
      
  }) |> do.call(rbind, args = _)
  }) |> do.call(rbind, args = _)

  split_col <- stringr::str_split_fixed(tcpl_results_cat_i$name, "_", 2)
  tcpl_results_cat_i <- cbind("chem" = split_col[, 1], "feat" = split_col[, 2], tcpl_results_cat_i[, -1])

  tcpl_results_cat_i <- tcpl_results_cat_i |>
    dplyr::mutate(
      minDose = min(conc, na.rm = TRUE),
      maxDose = max(conc, na.rm = TRUE),
      removal_reason = dplyr::case_when(
        hitcall < 0.9   ~ "low_hitcall",
        is.na(bmdl)     ~ "missing_bmdl",
        is.na(bmdu)     ~ "missing_bmdu",
        TRUE            ~ "kept"
      ),
      keep = removal_reason == "kept",
      bmd  = ifelse(keep, bmd,  NA),
      bmdl = ifelse(keep, bmdl, NA),
      bmdu = ifelse(keep, bmdu, NA)
    ) |>
    dplyr::ungroup() |>
    dplyr::filter(er < 0.99)

  tcpl_results_cat_i$exp_name <- exp_name

  # --- BMC plot ---
BMC_plot <- ggplot(tcpl_results_cat_i, aes(x = bmd, y = feat, colour = feat)) +
    geom_point(size = 3) +
    geom_errorbar(aes(xmin = bmdl, xmax = bmdu), width = 0.2) +
    scale_x_log10() +
    xlab("Best BMC (1MAD above vehicle control median) \u03BCM") +
    ylab("Feature Category") +
    theme_bw() +
    theme(
      legend.position = "none",
      axis.title.x = element_text(size = 17, margin = margin(t = 20)),
      axis.title.y = element_text(size = 17),
      axis.text.x  = element_text(size = 12, colour = "black"),
      axis.text.y  = element_text(size = 6, colour = "black", margin = margin(r = 5)),
      strip.text.x = element_text(size = 12, face = "bold"),
      strip.background = element_rect(fill = NA),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 1)
    ) +
    facet_wrap(vars(chem)) +
    ggtitle(paste0("Categorical BMC"))

ggsave(
    filename = file.path(plots, paste0("Categorical_BMC_NOTQRT", ".png")),
    plot = BMC_plot, width = 25, height = 35, units = "cm"
  )

  # --- Save tcpl results table ---
write_csv(
    tcpl_results_cat_i,
    file.path(
      pipeline_output_path, "tcplfit_results_cat_NOTSQRT",
      paste0("tcplfit_results_cat_0.9_common", ".csv")))
message("Done (category-level): ", basename(path))

```



